name: "Get TDRM CRQ Count"
description: "Creates and closes CRQ after the issue has been created."
inputs:
  totalCrq:
    description: "The total count of CRQ created in TDRM repo."
    required: true
  tableId:
    description: "Table Id on GCP Project"
    required: true
  datasetId:
    description: "Dataset Id on GCP Project"
    required: true
  projectId:
    description: "Project Id of GCP Project"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"